export const categories = [
    null,
    'quick chat',
    'time',
    'food',
    'drinks',
    'snacks',
    'activities',
    'emotions',
    'body',
    'clothing',
    'people',
    'describe',
    'kitchen',
    'school',
    'animals',
    'technology',
    'weather',
    'plants',
    'sports',
    'transport',
    'places',
    'position',
    'toys',
    'actions',
    'questions',
    'furniture',
    'hygiene',
    'numbers',
] as const;
export type ImageCategory = typeof categories[number];
